quarkus:
  application:
    name: camel-quarkus-xml
    version: 1.0.0
  swagger-ui:
    always-include: true
camel:
  context:
    name: camel-quarkus-xml-context
  main:
    routes-include-pattern: routes/myroutes.xml